name: My First CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Python application
        run: python3 hello.py

      - name: Run tests
        run: pytest

      - name: Show files
        run: ls -la
